[package]
name = "example-bindings"
version = "1.0.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
fp-bindgen-support = { path = "../../fp-bindgen-support", features = ["async"] }
once_cell = "1"
rmp-serde = "=1.0.0-beta.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
time = { version = "0.3", features = ["serde-human-readable"] }
uuid = { version = "0.8", features = ["serde"] }
