[package]
name = "example-bindings"
version = "1.0.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
fp-bindgen-support = { path = "../../fp-bindgen-support", features = ["async"] }
fp-bindgen-macros = { path = "../../macros" }
chrono = { version = "0.4.19", features = ["serde"] }
once_cell = "1"
rmp-serde = "=1.0.0-beta.1"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
